### ISSUE TITLE
Compile under ROS Melodic Ubuntu 18.04

### ISSUE THREAD

**Issue by h3ct0r** [AutonomyLab/parrot_arsdk#8]
Hi,

Is it planned to make a release for ROS Melodic under Ubuntu 18.04?

Thanks!

**Comment by thomas-bamford** [comment]
Yes, we are really hoping to upgrade this package to work under Ubuntu 18.04.

**Comment by thomas-bamford** [comment]
See https://github.com/AutonomyLab/bebop_autonomy/pull/168 and https://github.com/AutonomyLab/parrot_arsdk/pull/9. These compile together on Ubuntu 16.04 and will be tested on the vehicles in a few hours. Will try making this compatible with ROS Melodic on Ubuntu 18.04 in my spare time this week.

**Comment by thomas-bamford** [comment]
Fails to build with ROS Melodic because it is not included in the list of valid packages? See https://travis-ci.org/AutonomyLab/parrot_arsdk/builds/399658715?utm_source=github_status&utm_medium=notification for detailed error.

**Comment by thomas-bamford** [comment]
^reason for error above is that it needs to be released to ROS. See details [here.](http://wiki.ros.org/bloom)

Source compiles with ROS Melodic. Passes pre-release tests in ROS Melodic. I will attempt to release the binary in the next few days.

**Comment by thomas-bamford** [comment]
Released binary to Melodic successfully. Should be released by ROS soon.

**Comment by thomas-bamford** [comment]
Binary is available through ROS now.
`sudo apt install ros-melodic-parrot-arsdk`

**Comment by h3ct0r** [comment]
Thank you! :)
